stages:
  - build
  - test
  - validate
  - plan
  - deploy
  - destroy

default:
  tags:
    - runner-dummy

variables:
  TF_VAR_aws_vpc_id: $AWS_VPC
  TF_VAR_iam_instace_role: $AWS_IAM_ROLE
  TF_VAR_domain_name: $DOMAIN_NAME
  TF_VAR_docker_image: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG

docker_build:
  image: docker:cli
  stage: build
  services:
    - docker:dind
  variables:
    DOCKER_IMAGE_NAME: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
    DOCKER_DRIVER: overlay2 # Recommended by Docker
  before_script:
    - apk add --no-cache bash
    - docker login -u $CI_REGISTRY_USER -p $CI_JOB_TOKEN $CI_REGISTRY
  after_script:
    - docker rmi $(docker images -q) || true # Delete old images
  script:
    - docker build -t $DOCKER_IMAGE_NAME .
    - docker push $DOCKER_IMAGE_NAME
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
      exists:
        - Dockerfile

terraform_init:
  image:
    name: hashicorp/terraform:latest
    entrypoint: [""]
  stage: terraform
  variables:
    TF_BACKEND_ADDRESS: https://gitlab.com/api/v4/projects/$CI_PROJECT_ID/terraform/state/default
  before_script:
    - cd terraform
    - terraform init \
      -backend-config="address=$TF_BACKEND_ADDRESS"" \
      -backend-config="lock_address=$TF_BACKEND_ADDRESS/lock" \
      -backend-config="unlock_address=$TF_BACKEND_ADDRESS/lock" \
      -backend-config="username=$CI_JOB_TOKEN" \
      -backend-config="password=$CI_JOB_TOKEN" \
      -backend-config="lock_method=POST" \
      -backend-config="unlock_method=DELETE"
      -backend-config=retry_wait_min=5
    - terraform workspace new $CI_COMMIT_REF_NAME || terraform workspace select $CI_COMMIT_REF_NAME
  artifacts:
    paths:
      - $CI_PROJECT_DIR/.terraform
  only:
    - main

terraform_validate:
  image:
    name: hashicorp/terraform:latest
    entrypoint: [""]
  stage: validate
  before_script:
    - cd terraform
  script:
    - terraform --version
    - terraform validate
  only:
    - main

terraform_plan:
  image:
    name: hashicorp/terraform:latest
    entrypoint: [""]
  stage: plan
  before_script:
    - cd terraform
  script:
    - terraform plan -out=tfplan
  artifacts:
    paths:
      - tfplan
  only:
    - main

deploy:
  image:
    name: hashicorp/terraform:latest
    entrypoint: [""]
  stage: deploy
  before_script:
    - cd terraform
  script:
    - terraform apply -auto-approve tfplan
  artifacts:
    paths:
      - $CI_PROJECT_DIR/terraform.tfstate

terraform_destroy:
  image:
    name: hashicorp/terraform:latest
    entrypoint: [""]
  stage: destroy
  before_script:
    - cd terraform
  script:
    - terraform destroy -auto-approve
  when: manual
  needs: [terraform_apply]
  only:
    - main
